version: "3.7"

services:
  api:
    build: 
      context: ./apiserver
      dockerfile: Dockerfile
    container_name: comp322_team9_phase4_api
    volumes: 
      - ./apiserver:/usr/src/app
    ports: 
      - 18000:3000
    restart: always